### ISSUE TITLE
Finish Clang's implementation of __randomize_layout

### ISSUE THREAD

**Issue by kees** [KSPP/linux#101]
A Clang implementation of the `__randomize_layout` attribute needs to be finished so that Clang will have the same structure layout randomization as the existing GCC plugin:

https://reviews.llvm.org/D59254

**Comment by connorkuehl** [comment]
More up-to-date patches with more comprehensive test coverage as requested by upstream are here: https://github.com/connorkuehl/llvm-project/commits/randstruct 

Putting these on top of the latest development branch for LLVM will likely just have merge conflicts in things like a CMakeLists.txt or the compiler attribute generating code. It's never been anything too hairy.

If I recall correctly, C support is nearly done. I think there needs to be test coverage for alignment attributes and any bugs it uncovers need to go. I believe there's also a performance penalty that can be significantly reduced because we eagerly and unconditionally invoke some kind of AST matcher (I can't remember the finer details of this, as you can see from the dates it's been a long time). 

Aside from bugs and performance issues, this should be an accurate to-do list: https://github.com/connorkuehl/llvm-project/issues

Instructions for running unit tests are here: https://github.com/connorkuehl/llvm-project/blob/randstruct/clang/unittests/AST/RandstructTest.cpp#L14

Happy to help with any questions, etc.

**Comment by gwelymernans** [comment]
Done:

https://github.com/llvm/llvm-project/commit/3f0587d0c668202bb89d29a25432aa290e551a31
