### ISSUE TITLE
Zero call-used registers on function return

### ISSUE THREAD

**Issue by kees** [KSPP/linux#84]
As a defense against stale register contents being used in ROP attacks or as a side-channel or speculation path, the compiler could zero all used caller-used general registers at function exit, with virtually no performance impact (i.e. XORing general registers is highly pipelined).

`-fzero-call-used-regs=...` implementation:
- [x] GCC: [since v11](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=d10f3e900b0377b4760a090b0f90371bcef01686), [earlier development thread](https://gcc.gnu.org/pipermail/gcc-patches/2020-August/551607.html)
- [x] Clang: [bug](https://github.com/llvm/llvm-project/issues/37228)
  - [x] [x86](https://reviews.llvm.org/D110869): since v15+
  - [x] arm64: since 6.1+
- [x] Kernel: [since v5.15](https://git.kernel.org/linus/a82adfd5c7cb4b8bb37ef439aed954f9972bb618)

**Comment by madaidan** [comment]
The patch was renamed https://github.com/clearlinux-pkgs/gcc/blob/master/0001-x86-Add-mzero-caller.patch

**Comment by rengolin** [comment]
Clang thread: http://lists.llvm.org/pipermail/llvm-dev/2020-August/144082.html

**Comment by kees** [comment]
https://www.semanticscholar.org/paper/Clean-the-Scratch-Registers%3A-A-Way-to-Mitigate-Rong-Xie/6f2ce4fd31baa0f6c02f9eb5c57b90d39fe5fa13

**Comment by tsautereau-anssi** [comment]
The patch [landed](https://github.com/gcc-mirror/gcc/commit/d10f3e900b0377b4760a090b0f90371bcef01686) in GCC.

**Comment by kees** [comment]
The format is `-fzero-call-used-regs=[skip|used-gpr-arg|used-arg|all-gpr-arg|all-arg|used-gpr|all-gpr|used|all]`

This needs an implementation in Clang now.

**Comment by kees** [comment]
CBL issue: https://github.com/ClangBuiltLinux/linux/issues/20

**Comment by nickdesaulniers** [comment]
prefer: https://bugs.llvm.org/show_bug.cgi?id=37880

**Comment by kees** [comment]
https://lore.kernel.org/lkml/20210505191804.4015873-1-keescook@chromium.org/

**Comment by kees** [comment]
https://lore.kernel.org/lkml/20210714220129.844345-1-keescook@chromium.org/T/#u

**Comment by gwelymernans** [comment]
I've been tracking down the issue @nathanchance ran across with clang's implementation of `-fzero-call-used-regs`. I think I know what's going on, and it's gross.

If we take `arch/x86/kernel/probe_roms.c` for an example, the call to `find_oprom()` takes one argument. In the cases where it's called, the parameter is the same as one from the function that's calling it. As such, Clang seems to think it can omit saving the `%rdi` and `%rsi` registers, because they're supposedly going to remain the same when the function exits. But we're zeroing it out regardless.

**Comment by gwelymernans** [comment]
My current hypothesis:

> The function that's clearing the `%edi` register is static. I think that Clang looks at it and says to itself, "Hmm..Ya know, I can create pretty much any calling convention I want to with this thing, because no one will even know. MUWAHAHAHAHA!" And so even though the `%edi` register is caller-saved, it doesn't get saved because Clang determines either that it won't matter afterwards, or the value will be the original `%edi` value upon exit. If it were properly stored, then it would have been restored before return and the zeroing stuff wouldn't have been emitted.

**Comment by gwelymernans** [comment]
Due to #192, I'm becoming more and more wary about this feature. The zeroing of non-volatile registers is fraught with danger, so all of the `-fzero-call-used-regs=all*` flags are libel to fail wildly. The `used-arg*` flags will also fail for similar reasons. The only flags which seem even remotely safe to use are `used-gpr` and `used` (though I'm not totally convinced about the latter flag). And the term "used" is misleading, as that can still zero out non-volatile registers that weren't modified by the function.
