### ISSUE TITLE
Remove all strlcpy() uses in favor of strscpy()

### ISSUE THREAD

**Issue by kees** [KSPP/linux#89]
The `strlcpy()` function is dangerous in that the source buffer length is unbounded. This can cause memory over-reads, crashes, etc. It should be entirely removed from the kernel in favor of using `strscpy()`.

https://www.kernel.org/doc/html/latest/process/deprecated.html#strlcpy
https://lore.kernel.org/r/CAHk-=wgfRnXz0W3D37d01q3JFkr_i_uTL=V6A6G1oUZcprmknw@mail.gmail.com/

As with all of these kind of major refactorings, the changes are best split up into any special categories of manual steps, and then any special categories of automated steps. For example, I see at least two cases for `strlcpy()` -> `strscpy()`:

- [ ] replace all cases of `strlcpy()`'s return value being used and figure out how to correctly deal with it, since `strscpy()`'s return value is quite different
- [ ] replace all the "no return value checked" cases

**Comment by rperier** [comment]
Hi,
I am interested by this task, I propose to work on it.

**Comment by rperier** [comment]
We should do probably the same with nla_strlcpy(), because we have exactly the same kind of issues. lib/nlattr.c does not depend on external string library, so we cannot use subcalls to strscpy(), the solution is to propose a new nla_strscpy(), I think. Propably into a seperated contribution, what do you think ?

**Comment by kees** [comment]
I've detailed some thoughts on `nla_strlcpy()` here: https://github.com/KSPP/linux/issues/110

**Comment by rperier** [comment]
I still need to fix a build issue with cmd-exec.c (an objtool), a first preview is there: https://salsa.debian.org/rperier/linux-tree/-/tree/strlcpy_to_strscpy  (coccinelle FTW!)

It is okay as a "treewide" commit ? I mean, it is a direct replacement, so easy to review and easier to merge.

**Comment by kees** [comment]
> I still need to fix a build issue with cmd-exec.c (an objtool), a first preview is there: https://salsa.debian.org/rperier/linux-tree/-/tree/strlcpy_to_strscpy (coccinelle FTW!)

Very cool! As with all of these kind of major refactorings, the changes are best split up into any special categories of manual steps, and then any special categories of automated steps. For example, I see at least two cases for `strlcpy()` -> `strscpy()`:

- replace all cases of `strlcpy()`'s return value being used and figure out how to correctly deal with it, since `strscpy()`'s return value is quite different
- replace all the "no return value checked" cases

One thing I see in your treewide patch is Coccinelle doing some alias replacements, which MAY be okay, but might weird people out (e.g. `[0].` turned into `->`).

I would also include the Coccinelle script used in the commit message for the automated changes, and link to the [deprecation documentation](https://www.kernel.org/doc/html/latest/process/deprecated.html#strlcpy).

> It is okay as a "treewide" commit ? I mean, it is a direct replacement, so easy to review and easier to merge.

Short answer is "no", long answer is "kind of". ;) Given past efforts, usually these things are best split up by subsystem maintainer once you've stabilized what the changes will look like. Some times there will be stragglers, and things that need to be handled on a case-by-case basis. I (or maybe Gustavo?) can help with shepherding these changes into the kernel if subsystem maintainers aren't responsive.

I wrote a kind of bonkers "best-effort" tool, [`split-on-maintainers`](https://github.com/kees/kernel-tools/), that tries to generate separate patches from one big patch input. It works relatively well, but may need some hand-holding. That should make it easier to break up any of the logical steps.

**Comment by rperier** [comment]
Thanks for these details.
So, If I understood it well, for a beginning I can:
- Create a first commit that replaces all calls of strlcpy by strscpy, but only the calls with an handling of the return codes ("ret = strlcpy(dest,src, size);  if (ret)..."). I will include the cocci script and a link to the doc in the commit message.
- Create a second commit for all other cases (that do not handle the return code at all), so all the direct replacement in other words.

Once it is stabilized, I will take a look at your script to split these two commits into many commits, ideally, at least one commit per subsystem.

**Comment by rperier** [comment]
Hi !

I have pushed force my changes here https://salsa.debian.org/rperier/linux-tree/-/tree/strlcpy_to_strscpy : 
- I have created a commit for manual changes for all the the cases with the return values
- I have created a commit for all the other automatic changes, including the cocci script I have used (the script is not optimal, I am a beginner with cocci)

We have to be careful about the following changes:
- kernel/modules.c:2807,  because the returned size is added to the pointer "s", it will no longer work if -E2BIG is returned. As it is a central part of the kernel
- fs/kernfs/dir.c:  using strscpy changes the behaviour of public functions in some cases (typically in case of error), just to be sure that it is okay

These are changed by the first commit and it is not the final state, I have to rework them. I just want to warn about possible impacts in these subsystems.

Remaining work:
- I will use your script to split commits per maintainer
- I have to rework kernel/modules.c and fs/kernfs/dir.c 

Regards,
Romain

**Comment by rperier** [comment]
Hi !

I think I was not ready \o/ (psychologically), once splitted I get ~400 patches.
I have pushed an overview here: https://salsa.debian.org/rperier/linux-tree/-/tree/strlcpy_to_strscpy-splitted . This is the splitted version of the branch above. From my point of view it is reviewable.

I just had a daughter, so it means that everything will be merged for my daughter's 3rd birthday :D 

Regards,
Romain

**Comment by rperier** [comment]
ping ?

**Comment by kees** [comment]
There's a lot of patches here! :) I would send them maybe a dozen at a time; they look good from what I was able to spot check. Thanks!

**Comment by rperier** [comment]
Hi,

For the manual part, that's sent: https://www.openwall.com/lists/kernel-hardening/2021/02/22/12
This will probably trigger some discussions.

Romain

**Comment by kees** [comment]
And it is now gone!

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=57f22c8dab6b266ae36b89b073a4a33dea71e762
